spring:
     zipkin: 
           base-url: http://localhost:9411/              
     sleuth:
          sampler: 
             probability: 1
          traceId128: true                    
     rabbitmq:
          host: localhost
          port: 5672
          username: guest
          password: guest
